"""What the generated document says, and what it must never say.

A delivered weekly report opened on three lines nobody had asked for -- a
reporting period, a "prepared by" naming the assistant, and a readiness status
-- and ended on a rule of dashes printed as characters.

Only the second of those is a renderer defect, and it is pinned in
test_markdown_rendering.py. The first is what the document *said*: the body was
written with a header block describing the run that produced it. No code can
reject that, because a reporting period is ordinary prose and may be exactly
what a reader asked for. The instructions this skill gives are therefore the
control, which makes them product rather than commentary -- and a silent edit
that drops them brings the header block back with nothing failing.

These assertions quote the load-bearing sentences, read without their line
wrapping so that reflowing a paragraph is free. They are meant to be rewritten
deliberately, never removed.
"""
from __future__ import annotations

import unittest
from pathlib import Path

SKILL = (Path(__file__).resolve().parents[1] / "SKILL.md").read_text(encoding="utf-8")
PROSE = " ".join(SKILL.split())


class DocumentBodyContractTests(unittest.TestCase):
    def contains(self, sentence: str) -> None:
        self.assertIn(" ".join(sentence.split()), PROSE, sentence)

    def test_the_body_is_the_requested_document_and_opens_with_its_content(self):
        self.contains(
            "The body of the document is the document the user asked for, and nothing else."
        )
        self.contains("It opens with its title and goes straight into the content")
        self.contains("Do not open a report with a generated header block.")

    def test_the_excluded_class_covers_what_the_report_actually_carried(self):
        for excluded in (
            "A `Prepared by` or `Generated by` line",
            "an assistant, agent or model name",
            "a reporting period nobody asked for",
            "a review or workflow state",
            "a run, session or task reference",
            "the skill or script that produced the file",
            "any note about how the content was assembled",
        ):
            self.contains(excluded)
        self.contains("are all facts about the machinery, not about the subject")
        # The trailing "Durum: ..." line was the same defect in a second place.
        self.contains(
            "That holds at the end of the document and between its sections just as much"
            " as under the title."
        )

    def test_metadata_the_file_needs_is_carried_outside_the_body(self):
        self.contains("Metadata the file genuinely needs travels outside the body.")
        for field in ("`--title`", "`--lang`", "`author`", "`subject`", "`header`", "`footer`"):
            self.assertIn(field, PROSE, field)
        self.contains("None of them print in the body")

    def test_metadata_the_user_asked_for_stays_in_the_document(self):
        """Not a blanket deletion: a requested date is still the document's content."""
        self.contains(
            "A date, an author, a status or a period that the **user** asked for is the"
            " document's content: write it, in the terms the request used."
        )
        self.contains(
            "This rule is about what the system volunteers about itself, never about"
            " what was requested."
        )

    def test_a_horizontal_rule_is_documented_with_the_blank_line_it_needs(self):
        self.contains(
            "A horizontal rule is `---` on a line of its own with a **blank line before it**."
        )
        self.contains(
            "Without that blank line CommonMark reads the dashes as the underline of the"
            " line above, and that line becomes a heading instead"
        )
        self.contains("The rule characters themselves never print either way.")
        self.contains("A document also needs no rule to finish")


class LengthAndMathematicsContractTests(unittest.TestCase):
    """A run spent its whole budget rewriting one source to reach a page count.

    A requested length used to be checked after the fact: short of it, the
    document was "not finished" and the instruction was to deepen and render
    again *before delivering*. Nothing bounded that loop, so eleven rewrites of
    a 26 KB program later the time was gone, the last render was refused for an
    equation, and no file existed. The instructions are the control here too.

    A later run delivered a ten-page request as thirty-one pages, because the
    instructions let a document run past its requested length "because the subject
    needed the room" and nothing compared the count with the request. The renderer
    now refuses an over-length document when it is told the count, so what these
    assertions pin is the wording that tells the caller to pass it, and that a
    stated length is a limit as well as a target.
    """

    def contains(self, sentence: str) -> None:
        self.assertIn(" ".join(sentence.split()), PROSE, sentence)

    def test_a_requested_length_is_planned_for_and_the_revision_is_bounded(self):
        self.contains("it is met by planning, not by repair.")
        self.contains("A page of this document system holds about 450 words of running text.")
        self.contains("write the whole Markdown file once, and render it with the count the user gave")
        self.contains("Within a page of the request: deliver the file.")
        self.contains("Short by more than a page: revise once.")
        self.contains("There is no second revision.")
        self.assertNotIn("beyond it because the subject needed the room", PROSE)

    def test_a_stated_length_is_a_limit_the_renderer_enforces(self):
        self.contains("It is a limit as well as a target")
        self.contains("`--pages N` on `md_to_pdf.py` and on `report_pdf.py`")
        self.contains("never drop or raise it to get a file out")
        self.contains(
            "Over the request by more than a page: the render is refused as invalid input"
            " and nothing is written."
        )
        self.contains("A stated length is never outgrown because the subject needed the room.")
        self.contains("cut sections and detail, never the type size")

    def test_the_source_carries_real_line_breaks_and_no_front_matter(self):
        self.contains("Line breaks in the source are real line breaks.")
        self.contains("A Markdown source also carries no front matter")
        self.contains(
            "The renderer refuses a source with `\\n` escapes outside code, with a"
            " front-matter block, or that repeats its own sentences to reach a length."
        )
        self.contains("It names every such problem at once, writes nothing")
        self.contains("Do not pad with filler, repetition or blank pages.")

    def test_the_delivered_page_count_is_the_one_the_renderer_reported(self):
        self.contains("say the count the renderer reported.")
        self.contains("Never state a page count the renderer did not report.")
        self.assertNotIn("the document is not finished", PROSE)
        self.assertNotIn("Do this before delivering the file.", PROSE)

    def test_the_source_is_a_file_and_not_the_output_of_a_program(self):
        self.contains("Write the Markdown source as a file, exactly as it should read, and give the generator that file.")
        self.contains("Do not build the source inside a program.")
        self.contains("hides its exit status, so a refused render can look like success.")

    def test_equations_are_written_as_tex_and_the_subset_is_stated(self):
        self.contains("Write an equation as TeX.")
        self.contains("A dollar sign before a digit stays a dollar sign")
        self.contains("The supported subset:")
        self.contains("Outside the subset:")

    def test_a_refused_equation_is_repaired_never_disguised(self):
        self.contains("naming the line and the command of every such equation at once.")
        self.contains("Fix those equations and render again.")
        self.contains("an equation is never replaced by its source text, by a picture or by a plainer version of itself.")


class PictureLetteringContractTests(unittest.TestCase):
    """A Turkish book's generated cover was lettered in English, with an invented title.

    An image model letters whatever title it imagines, and no validator can read a
    picture, so the instruction is the only control: pictures carry no lettering,
    and the document's own title is text the renderer sets.
    """

    def contains(self, sentence: str) -> None:
        self.assertIn(" ".join(sentence.split()), PROSE, sentence)

    def test_a_picture_carries_no_lettering_and_the_title_is_real_text(self):
        self.contains("Lettering inside a picture is a claim about the document.")
        self.contains("Generate the picture with no lettering at all")
        self.contains("asking the image tool to exclude text, words and letters")
        self.contains("set the title, the author the user named and every label as real text in the document")

    def test_a_picture_that_must_carry_lettering_carries_the_documents_words(self):
        self.contains("A picture that must carry lettering carries exactly the words and language the document uses.")


if __name__ == "__main__":
    unittest.main()
