"""What the generated document says, and what it must never say.

A delivered weekly report opened on three lines nobody had asked for -- a
reporting period, a "prepared by" naming the assistant, and a readiness status
-- and ended on a rule of dashes printed as characters.

Only the second of those is a renderer defect, and it is pinned in
test_markdown_rendering.py. The first is what the document *said*: the body was
written with a header block describing the run that produced it. No code can
reject that, because a reporting period is ordinary prose and may be exactly
what a reader asked for. The instructions this skill gives are therefore the
control, which makes them product rather than commentary -- and a silent edit
that drops them brings the header block back with nothing failing.

These assertions quote the load-bearing sentences, read without their line
wrapping so that reflowing a paragraph is free. They are meant to be rewritten
deliberately, never removed.
"""
from __future__ import annotations

import unittest
from pathlib import Path

SKILL = (Path(__file__).resolve().parents[1] / "SKILL.md").read_text(encoding="utf-8")
PROSE = " ".join(SKILL.split())


class DocumentBodyContractTests(unittest.TestCase):
    def contains(self, sentence: str) -> None:
        self.assertIn(" ".join(sentence.split()), PROSE, sentence)

    def test_the_body_is_the_requested_document_and_opens_with_its_content(self):
        self.contains(
            "The body of the document is the document the user asked for, and nothing else."
        )
        self.contains("It opens with its title and goes straight into the content")
        self.contains("Do not open a report with a generated header block.")

    def test_the_excluded_class_covers_what_the_report_actually_carried(self):
        for excluded in (
            "A `Prepared by` or `Generated by` line",
            "an assistant, agent or model name",
            "a reporting period nobody asked for",
            "a review or workflow state",
            "a run, session or task reference",
            "the skill or script that produced the file",
            "any note about how the content was assembled",
        ):
            self.contains(excluded)
        self.contains("are all facts about the machinery, not about the subject")
        # The trailing "Durum: ..." line was the same defect in a second place.
        self.contains(
            "That holds at the end of the document and between its sections just as much"
            " as under the title."
        )

    def test_metadata_the_file_needs_is_carried_outside_the_body(self):
        self.contains("Metadata the file genuinely needs travels outside the body.")
        for field in ("`--title`", "`--lang`", "`author`", "`subject`", "`header`", "`footer`"):
            self.assertIn(field, PROSE, field)
        self.contains("None of them print in the body")

    def test_metadata_the_user_asked_for_stays_in_the_document(self):
        """Not a blanket deletion: a requested date is still the document's content."""
        self.contains(
            "A date, an author, a status or a period that the **user** asked for is the"
            " document's content: write it, in the terms the request used."
        )
        self.contains(
            "This rule is about what the system volunteers about itself, never about"
            " what was requested."
        )

    def test_a_horizontal_rule_is_documented_with_the_blank_line_it_needs(self):
        self.contains(
            "A horizontal rule is `---` on a line of its own with a **blank line before it**."
        )
        self.contains(
            "Without that blank line CommonMark reads the dashes as the underline of the"
            " line above, and that line becomes a heading instead"
        )
        self.contains("The rule characters themselves never print either way.")
        self.contains("A document also needs no rule to finish")


class LengthAndMathematicsContractTests(unittest.TestCase):
    """A run spent its whole budget rewriting one source to reach a page count.

    A requested length used to be checked after the fact: short of it, the
    document was "not finished" and the instruction was to deepen and render
    again *before delivering*. Nothing bounded that loop, so eleven rewrites of
    a 26 KB program later the time was gone, the last render was refused for an
    equation, and no file existed. The instructions are the control here too.
    """

    def contains(self, sentence: str) -> None:
        self.assertIn(" ".join(sentence.split()), PROSE, sentence)

    def test_a_requested_length_is_planned_for_and_the_revision_is_bounded(self):
        self.contains("it is met by planning, not by repair.")
        self.contains("A page of this document system holds about 450 words of running text.")
        self.contains("write the whole Markdown file once, and render it.")
        self.contains("Within a page of the request, or beyond it because the subject needed the room: deliver the file.")
        self.contains("Short by more than a page: revise once.")
        self.contains("There is no second revision.")

    def test_the_delivered_page_count_is_the_one_the_renderer_reported(self):
        self.contains("say the count the renderer reported.")
        self.contains("Never state a page count the renderer did not report.")
        self.assertNotIn("the document is not finished", PROSE)
        self.assertNotIn("Do this before delivering the file.", PROSE)

    def test_the_source_is_a_file_and_not_the_output_of_a_program(self):
        self.contains("Write the Markdown source as a file, exactly as it should read, and give the generator that file.")
        self.contains("Do not build the source inside a program.")
        self.contains("hides its exit status, so a refused render can look like success.")

    def test_equations_are_written_as_tex_and_the_subset_is_stated(self):
        self.contains("Write an equation as TeX.")
        self.contains("A dollar sign before a digit stays a dollar sign")
        self.contains("The supported subset:")
        self.contains("Outside the subset:")

    def test_a_refused_equation_is_repaired_never_disguised(self):
        self.contains("naming the line and the command of every such equation at once.")
        self.contains("Fix those equations and render again.")
        self.contains("an equation is never replaced by its source text, by a picture or by a plainer version of itself.")


if __name__ == "__main__":
    unittest.main()
