from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def dependency_available() -> bool:
    try:
        import openpyxl  # noqa: F401
        return True
    except ImportError:
        return False


@unittest.skipUnless(dependency_available(), "openpyxl is not installed")
class XlsxArtifactContractTests(unittest.TestCase):
    def test_validation_identity_survives_producer_path_replacement(self) -> None:
        import contextlib
        import importlib.util
        import io
        import os
        import zipfile
        from unittest.mock import patch
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source, output = root / "spec.json", root / "artifact.xlsx"
            source.write_text(json.dumps({'sheets': [{'name': 'Evidence', 'columns': [{'header': 'Value', 'type': 'text'}], 'rows': [['Generated bytes']]}]}), encoding="utf-8")
            built = subprocess.run([sys.executable, str(ROOT / "scripts/build_xlsx.py"), str(source), str(output)], capture_output=True, text=True, check=False)
            self.assertEqual(built.returncode, 0, built.stderr)
            generated = output.read_bytes()
            module_spec = importlib.util.spec_from_file_location("byte_identity_validator_xlsx", ROOT / "scripts/validate_xlsx.py")
            validator = importlib.util.module_from_spec(module_spec)
            sys.modules[module_spec.name] = validator
            module_spec.loader.exec_module(validator)
            original_zip = zipfile.ZipFile

            def replace_after_open(*args, **kwargs):
                opened = original_zip(*args, **kwargs)
                replacement = root / "replacement"
                replacement.write_bytes(b"a different invalid artifact")
                os.replace(replacement, output)
                return opened

            stdout, stderr = io.StringIO(), io.StringIO()
            with patch.object(validator.zipfile, "ZipFile", side_effect=replace_after_open), contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                result = validator.main([str(output)])
            self.assertEqual(result, 0, stderr.getvalue())
            frame = json.loads(stdout.getvalue().strip().splitlines()[-1])
            self.assertEqual(frame["subject"]["sha256"], hashlib.sha256(generated).hexdigest())
            self.assertEqual(frame["subject"]["bytes"], len(generated))
            self.assertNotEqual(output.read_bytes(), generated)

    def test_default_and_user_override_are_validated(self) -> None:
        for requested, expected in ((None, "IBM Plex Sans"), ("Avenir Next", "Avenir Next")):
            with tempfile.TemporaryDirectory() as directory:
                root = Path(directory)
                spec = {"sheets": [{"name": "Türkçe", "columns": [{"header": "Şehir", "type": "text"}], "rows": [["Şanlıurfa"], ["مرحبا بالعالم"]]}]}
                if requested is not None:
                    spec["font"] = requested
                source, output = root / "spec.json", root / "book.xlsx"
                source.write_text(json.dumps(spec, ensure_ascii=False), encoding="utf-8")
                built = subprocess.run([sys.executable, str(ROOT / "scripts/build_xlsx.py"), str(source), str(output)], capture_output=True, text=True, check=False)
                self.assertEqual(built.returncode, 0, built.stderr)
                produced = json.loads(built.stdout.strip().splitlines()[-1])
                self.assertEqual(produced["output"]["sha256"], hashlib.sha256(output.read_bytes()).hexdigest())
                checked = subprocess.run([sys.executable, str(ROOT / "scripts/validate_xlsx.py"), str(output)], capture_output=True, text=True, check=False)
                self.assertEqual(checked.returncode, 0, checked.stderr)
                validation = json.loads(checked.stdout.strip().splitlines()[-1])
                self.assertEqual(validation["subject"]["sha256"], produced["output"]["sha256"])
                self.assertEqual(validation["typography"]["family"], expected)
                self.assertEqual(validation["typography"]["fallbacks"], ["IBM Plex Sans Arabic"])


if __name__ == "__main__":
    unittest.main()
